pipeline {
    agent { node { label 'agent1' } }

    stages {
        stage('Init') {
            steps {
                sh '''
                    terraform init
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                   terraform plan
                '''
            }
        }
    }
    post { 
        always { 
            echo 'I will always run wether job is success or not'
        }
        success{
            echo 'I will run only when job is success'
        }
        failure{
            echo 'I will run when job failure'
        }
    }
}